///////////////////////////////////////////////////////////
//  CBuildingObject.as
//  Macromedia ActionScript Implementation of the Class CBuildingObject
//  Generated by Enterprise Architect
//  Created on:      15-二月-2012 10:17:54
//  Original author: johnnyeven
///////////////////////////////////////////////////////////

package Apollo.Objects
{
	import Apollo.Objects.CMovieObject;
	import Apollo.Controller.CBaseController;
	import Apollo.Objects.dependency.CDependency;

	/**
	 * @author johnnyeven
	 * @version 1.0
	 * @created 15-二月-2012 10:17:54
	 */

	public class CBuildingObject extends CMovieObject
	{
		protected var buildingFlag: int;
		protected var buildingName: String;
		protected var level: uint;
		protected var maxLevel: uint;
		/**
		 * 消耗的资源
		 */
		protected var consumeList: Array;
		/**
		 * 产出的资源
		 */
		protected var produceList: Array;
		protected var dependency: CDependency;

		/**
		 * 
		 * @param _ctrl
		 */
		public function CBuildingObject(_ctrl:CBaseController, _buildingFlag: int)
		{
			super(_ctrl);
			buildingFlag = _buildingFlag;
		}

		/**
		 * 
		 * @param level
		 */
		public function levelUp(value: uint = 1): Boolean;
		{
			if (level >= maxLevel)
			{
				return false;
			}
			else
			{
				level += value;
				return true;
			}
		}

		public function get level(): uint
		{
			return level;
		}

		public function get dependency(): CDependency
		{
			return dependency;
		}

		public override function RenderObject(): void
		{
		}

		public override function Upgrade(): void
		{
		}

		public override function Destroy(): Boolean
		{
		}

	} //end CBuildingObject

}