///////////////////////////////////////////////////////////
//  CCollectionBuilding.as
//  Macromedia ActionScript Implementation of the Class CCollectionBuilding
//  Generated by Enterprise Architect
//  Created on:      15-二月-2012 10:17:54
//  Original author: johnnyeven
///////////////////////////////////////////////////////////

package apollo.objects
{
	import apollo.objects.CBuildingObject;
	import apollo.controller.CBaseController;
	import apollo.network.data.CResourceParameter;
	import apollo.center.CResourceCenter;

	/**
	 * @author johnnyeven
	 * @version 1.0
	 * @created 15-二月-2012 10:17:54
	 */

	public class CCollectionBuilding extends CBuildingObject
	{
		/**
		 * 消耗的资源
		 */
		protected var _consumeList: Vector.<CResourceParameter>;
		/**
		 * 产出的资源
		 */
		protected var _produceList: Vector.<CResourceParameter>;

		/**
		 * 
		 * @param _ctrl
		 */
		public function CCollectionBuilding(_ctrl:CBaseController, _buildingId: uint)
		{
			super(_ctrl, _buildingId);
			_consumeList = new Vector.<CResourceParameter>();
			_produceList = new Vector.<CResourceParameter>();
		}
		
		public function get consumeList(): Vector.<CResourceParameter>
		{
			return _consumeList;
		}
		
		public function get produceList(): Vector.<CResourceParameter>
		{
			return _produceList;
		}
		
		public function addConsumeResource(resource: CResourceParameter, sysnc: Boolean = true): void
		{
			if (resource != null)
			{
				if (resource.resourceModified > 0)
				{
					resource.resourceModified *= -1;
					CONFIG::DebugMode
					{
						trace("Warning: ConsumeResource的resourceModified大于零，已自动更正");
					}
				}
				_consumeList.push(resource);
				if (sysnc)
				{
					CResourceCenter.getInstance().modifyResource(resource.resourceId, resource.resourceModified);
				}
			}
		}
		
		public function addProduceResource(resource: CResourceParameter, sysnc: Boolean = true): void
		{
			if (resource != null)
			{
				if (resource.resourceModified < 0)
				{
					resource.resourceModified *= -1;
					CONFIG::DebugMode
					{
						trace("Warning: ProduceResource的resourceModified小于零，已自动更正");
					}
				}
				_produceList.push(resource);
				if (sysnc)
				{
					CResourceCenter.getInstance().modifyResource(resource.resourceId, resource.resourceModified);
				}
			}
		}

	}

}