///////////////////////////////////////////////////////////
//  CNPCCharacter.as
//  Macromedia ActionScript Implementation of the Class CNPCCharacter
//  Generated by Enterprise Architect
//  Created on:      15-二月-2012 10:17:55
//  Original author: johnnyeven
///////////////////////////////////////////////////////////

package Apollo.Objects
{
	import Apollo.Controller.CBaseController;
	import Apollo.Objects.CCharacterObject;
	import Apollo.Script.CScript;
	
	import flash.events.Event;

	/**
	 * @author johnnyeven
	 * @version 1.0
	 * @created 15-二月-2012 10:17:55
	 */

	public class CNPCCharacter extends CCharacterObject
	{
		//protected var missionConfig: CMissionConfig;
		protected var _script: CScript;

		public function CNPCCharacter(npcId: String, _ctrl: CBaseController = null, _direction: uint = CDirection.DOWN)
		{
			super(_ctrl, _direction);
			objectId = npcId;
			
			//初始化脚本解释器
			_script = new CScript(npcId, this, _ctrl.perception.scene);
		}
		
		public function get script(): CScript
		{
			return _script;
		}

		public function loadMissionScript(): void
		{
		}
/*
		public function get missionConfig(): CMissionConfig
		{
		}
*/
		/**
		 * 
		 * @param evt
		 */
		private function parseMissionScript(evt:Event): void
		{
		}

	} //end CNPCCharacter

}