///////////////////////////////////////////////////////////
//  CBuildingController.as
//  Macromedia ActionScript Implementation of the Class CBuildingController
//  Generated by Enterprise Architect
//  Created on:      15-二月-2012 10:17:53
//  Original author: Administrator
///////////////////////////////////////////////////////////

package Apollo.Controller
{
	import Apollo.Controller.CBaseController;

	/**
	 * @author Administrator
	 * @version 1.0
	 * @created 15-二月-2012 10:17:53
	 */

	public class CBuildingController extends CBaseController
	{
		public function CBuildingController(){

		}

	} //end CBuildingController

}