///////////////////////////////////////////////////////////
//  CCharacterData.as
//  Macromedia ActionScript Implementation of the Class CCharacterData
//  Generated by Enterprise Architect
//  Created on:      15-二月-2012 10:17:54
//  Original author: Administrator
///////////////////////////////////////////////////////////

package Apollo.utils
{
	import Apollo.Network.CControlConnection;
	import flash.utils.Dictionary;
	import Apollo.Controller.KeyCode;


	/**
	 * @author Administrator
	 * @version 1.0
	 * @created 15-二月-2012 10:17:54
	 */

	public class CCharacterData
	{
		public var camp: uint = 0;
		public var uid: String = '';
		public var uname: String;
		public var level: uint;
		private var missionList: Array;
		private var _skillList: Dictionary;
		private static var instance: CCharacterData;
		private static var allowInstance: Boolean = false;

		public function CCharacterData()
		{
			_skillList = new Dictionary();
			_skillList[KeyCode.F1] = new Array("skill1", 0);
			_skillList[KeyCode.F2] = new Array("skill2", 0);
			_skillList[KeyCode.F3] = new Array("skill3", 1);	//2级
			_skillList[KeyCode.F4] = new Array("skill4", 0);
			_skillList[KeyCode.F5] = new Array("skill5", 0);
			_skillList[KeyCode.F6] = new Array("skill6", 0);
			_skillList[KeyCode.F7] = new Array("skill7", 0);
			_skillList[KeyCode.F8] = new Array("skill8", 0);
			_skillList[KeyCode.F9] = new Array("skill9", 0);
		}
		
		public function getPlayerData(): void
		{
			
		}
		
		public function get skillList(): Dictionary
		{
			return _skillList;
		}

		public function get AllMissionList(): Array
		{
			return missionList;
		}

		public function get CanSeeMissionList(): Array
		{
			return missionList;
		}

		public function initMissionList(): void
		{
		}

	} //end CCharacterData

}