///////////////////////////////////////////////////////////
//  CBuildingObject.as
//  Macromedia ActionScript Implementation of the Class CBuildingObject
//  Generated by Enterprise Architect
//  Created on:      15-二月-2012 10:17:54
//  Original author: johnnyeven
///////////////////////////////////////////////////////////

package Apollo.Objects
{
	import Apollo.Objects.CMovieObject;
	import Apollo.Controller.CBaseController;

	/**
	 * @author johnnyeven
	 * @version 1.0
	 * @created 15-二月-2012 10:17:54
	 */

	public class CBuildingObject extends CMovieObject
	{
		protected var level: uint = 1;
		protected var levelUpResource: Array;
		protected var health: Number;
		protected var healthMax: Number;

		/**
		 * 
		 * @param _ctrl
		 */
		public function CBuildingObject(_ctrl:CBaseController)
		{
		}

		/**
		 * 
		 * @param health
		 */
		public function set health(health:Number): void
		{
		}

		public function get health(): Number
		{
		}

		/**
		 * 
		 * @param healthMax
		 */
		public function set healthMax(healthMax:Number): void
		{
		}

		public function get healthMax(): Number
		{
		}

		/**
		 * 
		 * @param level
		 */
		public function set level(level:uint): void
		{
		}

		public function get level(): uint
		{
		}

		public function get levelUpResource(): Array
		{
		}

		/**
		 * 
		 * @param _resource
		 */
		public function set levelUpResource(_resource:Array): void
		{
		}

		public override function RenderObject(): void
		{
		}

		public override function Upgrade(): void
		{
		}

		public override function Destroy(): Boolean
		{
		}

	} //end CBuildingObject

}