///////////////////////////////////////////////////////////
//  CCollectionBuilding.as
//  Macromedia ActionScript Implementation of the Class CCollectionBuilding
//  Generated by Enterprise Architect
//  Created on:      15-二月-2012 10:17:54
//  Original author: johnnyeven
///////////////////////////////////////////////////////////

package Apollo.Objects
{
	import Apollo.Objects.CBuildingObject;

	/**
	 * @author johnnyeven
	 * @version 1.0
	 * @created 15-二月-2012 10:17:54
	 */

	public class CCollectionBuilding extends CBuildingObject
	{
		private var rate: uint = 100;
		private var requireResource: Array;
		private var productResource: Array;
		private var workers: CWorkerList;
		private var workerAbility: uint;
		private var productionCycle: uint;

		public function CCollectionBuilding(){

		}

		/**
		 * 
		 * @param _ctrl
		 */
		public function CCollectionBuilding(_ctrl:CBaseController)
		{
		}

		public function GenerateWorker(): uint
		{
		}

		/**
		 * 
		 * @param id
		 */
		public function GetWorker(id:uint): CWorkerCharacter
		{
		}

		/**
		 * 
		 * @param _name
		 */
		public function GetWorker(_name:String): CWorkerCharacter
		{
		}

		public function get productResource(): Array
		{
		}

		/**
		 * 
		 * @param _resource
		 */
		public function set productResource(_resource:Array): void
		{
		}

		/**
		 * 
		 * @param rate
		 */
		public function set rate(rate:uint): void
		{
		}

		public function get rate(): uint
		{
		}

		public function get requireResource(): Array
		{
		}

		/**
		 * 
		 * @param _resource
		 */
		public function set requireResource(_resource:Array): void
		{
		}

		/**
		 * 
		 * @param workerAbility
		 */
		public function set workerAbility(workerAbility:uint): void
		{
		}

		public function get workerAbility(): uint
		{
		}

		/**
		 * 
		 * @param _rate
		 */
		public function ChangeRate(_rate:uint): void
		{
		}

	} //end CCollectionBuilding

}