///////////////////////////////////////////////////////////
//  Action.as
//  Macromedia ActionScript Implementation of the Class Action
//  Generated by Enterprise Architect
//  Created on:      15-二月-2012 13:52:06
//  Original author: Administrator
///////////////////////////////////////////////////////////

package apollo.controller
{


	/**
	 * @author Administrator
	 * @version 1.0
	 * @created 15-二月-2012 13:52:06
	 */

	public class Action
	{
		static public var STOP: int = 0;
		static public var SIT: int = 1;
		static public var MOVE: int = 2;
		static public var ATTACK: int = 6;
		static public var DIE: int = 10;
		static public var RELIVE: int = 13;

		public function Action()
		{

		}

	} //end Action

}