///////////////////////////////////////////////////////////
//  CBuildingController.as
//  Macromedia ActionScript Implementation of the Class CBuildingController
//  Generated by Enterprise Architect
//  Created on:      15-二月-2012 10:17:53
//  Original author: Administrator
///////////////////////////////////////////////////////////

package apollo.controller
{
	import apollo.objects.CBuildingObject;
	import flash.events.Event;
	import flash.events.MouseEvent;
	
	import ui.components.*;
	import apollo.graphics.CGraphicPool;

	/**
	 * @author Administrator
	 * @version 1.0
	 * @created 15-二月-2012 10:17:53
	 */

	public class CBuildingController extends CBaseController
	{
		public function CBuildingController(per: CPerception)
		{
			super(per);
		}
		
		override public function calcAction(): void
		{
			
		}

		override public function setupListener(): void
		{
			_controlObject.addEventListener(MouseEvent.CLICK, onObjectClick, false, 0, true);
		}

		override public function removeListener(): void
		{
			_controlObject.removeEventListener(MouseEvent.CLICK, onObjectClick);
		}
		
		private function onObjectClick(evt: MouseEvent): void
		{
			var menu: UIMenu = new UIMenu();
			menu.addMenuItem("升级1", onMenu1);
			menu.addMenuItem("升级2", onMenu1);
			menu.addMenuItem("升级3", onMenu1);
			_controlObject.addChild(menu);
		}
		
		private function onMenu1(evt: MouseEvent): void
		{
			trace('1 click');
		}

	} //end CBuildingController

}