///////////////////////////////////////////////////////////
//  CStaticObject.as
//  Macromedia ActionScript Implementation of the Class CStaticObject
//  Generated by Enterprise Architect
//  Created on:      15-二月-2012 10:17:55
//  Original author: johnnyeven
///////////////////////////////////////////////////////////

package utils
{
	import flash.display.Sprite;

	/**
	 * 
	 * @author johnnyeven
	 * @version 1.0
	 * @created 15-二月-2012 10:17:55
	 */

	public class CStaticObject extends Sprite
	{
		public function CStaticObject()
		{
			super();
			tabEnabled = false;
			tabChildren = false;
		}

	} //end CStaticObject

}