///////////////////////////////////////////////////////////
//  CFunctionBuilding.as
//  Macromedia ActionScript Implementation of the Class CFunctionBuilding
//  Generated by Enterprise Architect
//  Created on:      15-二月-2012 10:17:54
//  Original author: Administrator
///////////////////////////////////////////////////////////

package Apollo.Objects
{
	import Apollo.Objects.CGameObject;
	import Apollo.Objects.CBuildingObject;

	/**
	 * @author Administrator
	 * @version 1.0
	 * @created 15-二月-2012 10:17:54
	 */

	public class CFunctionBuilding extends CBuildingObject
	{
		protected var sequence: Array;
		protected var maxSequence: uint = 1;

		public function CFunctionBuilding(){

		}

		/**
		 * 
		 * @param _ctrl
		 */
		public function CFunctionBuilding(_ctrl:CBaseController)
		{
		}

		/**
		 * 
		 * @param o
		 */
		public function AddToSequence(o:CGameObject): void
		{
		}

		/**
		 * 
		 * @param o
		 */
		public function RemoveFromSequence(o:CGameObject): void
		{
		}

	} //end CFunctionBuilding

}